version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    command: mongod --smallfiles --logpath=/dev/null

  server:
    build: ./server
    env_file:
      - ./server/.env
    expose:
      - "4000"
    environment:
      API_HOST: "http://localhost"
      APP_SERVER_PORT: "4000"
    ports:
      - "4000:4000"
    volumes:
      - ./server/src:/src/app/crud-project-server/src
    links:
      - mongodb
    depends_on:
      - mongodb
    command: npm run dev

  client:
    build: ./client
    env_file:
      - ./client/.env
    environment:
      - REACT_APP_PORT="3000"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/src/app/crud-project-client/src
      - ./client/public:/src/app/crud-project-client/public
    links:
      - server
    command: npm run start